### ISSUE TITLE
Broken dependencies (aka: is this project still active ?)

### ISSUE THREAD

**Issue by NinjaCross** [ni-c/heimcontrol.js#140]
I just tried to compile the project, but as far as I can see, some dependencies are obsolete and cannot be updated because the related project is discontinued  or broken (i.e. piswitch, duino).
Is this project still active ?
Is there a plan to fix the broken dependencies ?

**Comment by tjanson** [comment]
It's been a few years since someone took care of this project. If you want to make it work, feel free to do so (I'm not sure how much needs to be done).

I've mentioned [a few possible alternatives in this comment](https://github.com/ni-c/heimcontrol.js/issues/133#issuecomment-193442921), but those are far larger frameworks. That may or may not fit your needs.
